apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-website
  labels:
    app: nginx-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-website
  template:
    metadata:
      labels:
        app: nginx-website
    spec:
      containers:
      - name: nginx
        image: nginx:1.27-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: website-content
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
        - name: website-content
          mountPath: /usr/share/nginx/html/style.css
          subPath: style.css
      volumes:
      - name: website-content
        configMap:
          name: website-content
